- name: install npm with nodejs
  apt: name=nodejs state=present

- name: make sure the latest npm is installed
  command: npm install -g npm

- name: npm install vorlonjs
  npm: name=vorlon global=yes

- name: add vorlonjs into supervisor config
  template:
  args:
    src: supervisord.conf.j2
    dest: /etc/supervisor/conf.d/supervisord_vorlon.conf
  sudo_user: root
  register: supervisor_config

- name: restart supervisor
  sudo_user: root
  supervisorctl:
    name: vorlon
    state: restarted

- name: add vorlon path to nginx config
  template:
    force: yes
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/vorlon.conf
  sudo_user: root
  notify:
    - reload nginx